version: '3'

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "8000:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-entrypoints.yml:/etc/traefik/traefik.yml # mount config with entrypoints

  catapp:
     image: mikesir87/cats:1.0
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catapp.rule=Host(`catapp.localhost`)" # to access
      - "traefik.http.routers.catapp.entrypoints=web" # which entrypoint to target
      - "traefik.http.services.catapp.loadbalancer.server.port=5000" # which port in catapp is being exposed
