version: '3'

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "8000:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

  catapp:
     image: mikesir87/cats:1.0
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.catapp.rule=Host(`catapp.localhost`)"
       - "traefik.http.routers.catapp.service=catapp"
       - "traefik.http.routers.catapp.entrypoints=web"
       - "traefik.http.routers.catapp.middlewares=test-compress"
       - "traefik.http.services.catapp.loadbalancer.server.port=5000"
       - "traefik.http.middlewares.test-compress.compress=true"
